version: '3'

x-backend-env:
  &backend-env
    APP_ENVIRONMENT: ${APP_ENVIRONMENT}
    APP_DEBUG: ${APP_DEBUG}
    APP_LOG_LEVEL: ${APP_LOG_LEVEL}
    APP_API_URL: ${APP_API_URL}
    APP_CLIENT_URL: ${APP_CLIENT_URL}

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      <<: *backend-env
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_LABEL: "backend"
    ports:
     - "8080:8000"
    depends_on:
      - postgres_db
      - minio

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_URL: ${APP_API_URL}
    ports:
      - "5173:5173"

  postgres_db:
    image: postgres:16
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/postgres_db:/var/lib/postgresql/data

  minio:
    restart: on-failure
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - 9000
      - 9001
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    command: server --address ":9000" --console-address ":9001" /export
    volumes:
      - ./data/minio:/export
      - ./data/minio:/root/.minio
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
