version: '3'

x-backend-env:
  &backend-env
    APP_DB_HOST: ${DB_HOST}
    APP_DB_PORT: ${DB_PORT}
    APP_DB_USER: ${DB_USER}
    APP_DB_NAME: ${DB_NAME}
    APP_DB_PASSWORD: ${DB_PASSWORD}
    APP_ENVIRONMENT: ${APP_ENVIRONMENT}
    APP_DEBUG: ${APP_DEBUG}
    APP_LOG_LEVEL: ${APP_LOG_LEVEL}

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      <<: *backend-env
      APP_LABEL: "backend"
    ports:
     - "8080:8000"
    depends_on:
      - postgres_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_URL: ${APP_API_URL}
    ports:
      - "5173:5173"

  postgres_db:
    image: postgres:16
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/postgres_db:/var/lib/postgresql/data
