# Generated by Django 5.0.7 on 2024-09-29 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import polls.utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название опроса')),
                ('channel', models.PositiveIntegerField(choices=[(1, 'SMS'), (2, 'E-mail'), (3, 'Web')], default=3, verbose_name='Канал')),
                ('status', models.PositiveIntegerField(choices=[(2, 'Активный'), (3, 'Закончен'), (4, 'Удалён'), (5, 'Черновик')], default=5, verbose_name='Статус опроса')),
                ('date_start', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата начала опроса')),
                ('date_finish', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата окончания опроса')),
                ('communications_total', models.PositiveIntegerField(default=0, verbose_name='Общее количество коммуникаций на опрос')),
                ('stats_sent', models.PositiveIntegerField(default=0, editable=False, verbose_name='Отправлено')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено')),
                ('mail_title', models.CharField(default='Торговая сеть Бананчик: Опрос', max_length=255, verbose_name='Заголовок письма')),
                ('mail_preheader', models.CharField(default='Приглашаем вас пройти опрос', max_length=255, verbose_name='Прехедер письма')),
                ('mail_content', models.TextField(default='<div><strong>Здравствуйте!</strong><br><br></div><div>Спасибо, что выбираете магазины «Бананчик».</div><div>Поделитесь Вашим мнением что необходимо исправить или улучшить, какие у нас слабые и сильные стороны — это поможет сделать «Бананчик» лучше.</div>', verbose_name='Текст письма')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['modified'],
            },
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.PositiveIntegerField(choices=[(1, 'Свободная форма'), (2, 'Одиночный выбор'), (3, 'Множественный выбор')], verbose_name='Тип вопроса')),
                ('title', models.TextField(verbose_name='Текст вопроса')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('image', models.ImageField(default=None, null=True, storage=polls.utils.storage.S3ProxyFileSystemStorage(), upload_to='questions', verbose_name='Изображение')),
                ('has_skip_answer', models.BooleanField(default=False, verbose_name='Присутствует ответ "Затрудняюсь ответить"')),
                ('is_last_page', models.BooleanField(default=False, verbose_name='Последняя страница опроса')),
                ('end_message_text', models.TextField(blank=True, null=True, verbose_name='Текст завершающего сообщения')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.poll', verbose_name='Опрос')),
            ],
            options={
                'ordering': ['modified_at'],
            },
        ),
        migrations.CreateModel(
            name='PollQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollquestion', verbose_name='Вопрос')),
            ],
            options={
                'ordering': ['modified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['status'], name='polls_poll_status_b99f43_idx'),
        ),
    ]
