# Generated by Django 5.0.7 on 2024-10-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollquestion',
            name='end_message_text',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='is_last_page',
        ),
    ]
