# Generated by Django 5.1.2 on 2024-11-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_pollquestion_end_message_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.PositiveIntegerField(choices=[(1, 'Условия')], verbose_name='Тип')),
                ('condition_id', models.CharField(choices=[('conditions_trigger_item_receipt_sum', 'Сумма чека')], default='conditions_trigger_item_receipt_sum', max_length=255, verbose_name='Условие')),
                ('condition_value', models.JSONField(verbose_name='Содержание условия')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='polls.poll', verbose_name='Опрос')),
            ],
            options={
                'ordering': ['poll'],
            },
        ),
    ]
