# Generated by Django 5.1.2 on 2024-12-12 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('polls', '0003_pollconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollquestion',
            name='has_skip_answer',
        ),
        migrations.CreateModel(
            name='PollProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Уникальный ID опроса')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Активный'), (2, 'Закончен')], default=1, verbose_name='Статус')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Клиент')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.poll', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='PollProgressAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Текстовый ответ')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollquestionanswer', verbose_name='Вариант ответа')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.poll', verbose_name='Опрос')),
                ('poll_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollprogress', verbose_name='Прогресс клиента')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollquestion', verbose_name='Вопрос')),
            ],
        ),
    ]
