# Generated by Django 5.1.2 on 2024-11-21 10:38

from django.db import migrations


def assign_permissions_to_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    from users.models import ROLE_PERMISSIONS

    for role, get_permissions in ROLE_PERMISSIONS.items():
        group, _ = Group.objects.get_or_create(name=role)
        permissions = get_permissions()
        for perm in permissions:
            group.permissions.add(perm.id)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(assign_permissions_to_groups),
    ]
