# Generated by Django 5.1.2 on 2024-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер карты')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('gender', models.PositiveIntegerField(choices=[(0, 'не указан'), (1, 'мужской'), (2, 'женский')], default=0, verbose_name='Пол')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('last_communication', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней коммуникации')),
            ],
        ),
    ]
