name: Backend CI

on:
  pull_request:
    branches:
      - develop

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      run_job: ${{ steps.changes.outputs.run_job }}

    steps:
      - uses: actions/checkout@v4

      - name: Check for changes in backend
        id: changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^backend/'
          then
            echo "::set-output name=run_job::true"
          else
            echo "::set-output name=run_job::false"
          fi
        shell: bash

  build-backend:
    needs: check_changes
    if: needs.check_changes.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: danya151q/feedback:pull_request

  lint-backend:
    needs: [ build-backend ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull image
        run: docker pull danya151q/feedback:pull_request

      - name: Run linters
        run: |
          # TODO