name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        working-directory: frontend
        run: docker build -f Dockerfile -t frontend:latest .

  lint-frontend:
    runs-on: ubuntu-latest
    needs: [build-frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run linters
        run: |
          # TODO

  test-frontend:
    runs-on: ubuntu-latest
    needs: [lint-frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          # TODO
